### ISSUE TITLE
RuntimeError: Specified protocol version (448) not found

### ISSUE THREAD

**Issue by mfp20** [pyfa-org/Phobos#10]
The full error row is:

`RuntimeError: Specified protocol version (448) not found in C:\Users\Willy\AppData\Local\CCP\EVE\c_program_files_(x86)_steam_steamapps_common_eve_online_sharedcache_tq_tranquility\cache\MachoNet\87.237.38.200`

Any clue?

**Comment by DarkFenX** [comment]
This is reverence being outdated, so it's an upstream bug. Just create the folder it needs (copy folder of another IP). Given there will be 64 bit client soon and reverence will stop working, I am closing this issue.

We will have to redo data dumping from scratch.
