### ISSUE TITLE
Missing dogma data?

### ISSUE THREAD

**Issue by Robert-Hucks** [pyfa-org/Phobos#13]
Hi there,

I've been trying to use this tool for fetching all of the Dogma related data but there appears to be files missing when I run the command. I believe there should be `dogmaexpressions` and `dogmaoperands` files which are missing entirely, and probably related is the `dogmaeffects` which is missing the `preExpression`/`postExpression` fields.

Is this data available to be pulled from the client?

Appreciate any help, thanks.

Just for reference this is the command I've been running, nothing special:
```console
python run.py --eve="C:\EVE" --server="tq" --json="D:\phobos_output"
```

**Comment by DarkFenX** [comment]
This data has been removed from the client, and replaced by `modifierInfo` in `fsd_binary/dogmaeffects.json`.
