### ISSUE TITLE
Logistic Frigates and Command Destroyer traits missing

### ISSUE THREAD

**Issue by Altrue** [pyfa-org/Phobos#7]
The generated phbtraits.json doesn't contain traits data for the (relatively) new Logistic Frigates and Command Destroyers.

(Still, phbtraits has been more than helpful for me :) )

**Comment by blitzmann** [comment]
I am unsure of the problem here. They are present in the latest phobos dump of tq and sisi. Can you be more specific on what you are trying to accomplish? Is it all ships in those groups missing, or just a few? Are you trying to dump SISI or TQ data? etc

**Comment by Altrue** [comment]
I tried a dump of TQ using the phbtraits container, and the resulting JSON doesn't make any mention of these ships' typeID.

If you tell me that they are present in the latest dump, then I must have made a mistake somewhere in the various arguments. Probably picked an older version of the client or something, but even after trying out various combinaisons, I can't seem to get up-to-date data.

The readme is 11 months old, could it be possible that something about it isn't up-to-date anymore?

**Comment by blitzmann** [comment]
Glad to hear it works now. Yes, the new launcher moved some stuff around, so it's very possible that the paths were incorrect and pointing to the old client or something. I'll take a look at the README later and see if there is anything that needs to be updated.

**Comment by blitzmann** [comment]
Also, updated README to better reflect current status of eve launcher / path issues. Hope it helps =)

**Comment by Altrue** [comment]
You're the best :)
